os: linux
language: 
- cpp

jobs:
  include:
  - name: "building"
    before_install:
    - sudo apt-get update -qq
    script:
     - mkdir build
     - cd build
     - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
     - ./runtests_cpppcap
#    - cmake -H. -B_build -DBUILD_TESTS=ON
#    - cmake --build _build
#    - cmake --build _build --target analysis_form_dump
