os: linux
language: 
- cpp

jobs:
  include:
  - name: "building"
  before_install:
  - sudo apt-get update -qq
    script:
    - cmake -H. -B_build -DBUILD_TESTS=ON
    - cmake --build _build
    - cmake --build _build --target analysis_form_dump
